#!/bin/bash

code_folder_name=zend
workdir=$(pwd)



if [ -z $1 ]
then
	echo "Please specify a name for the container"
	exit 1
fi

php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
php -r "if (hash_file('SHA384', 'composer-setup.php') === '7228c001f88bee97506740ef0888240bd8a760b046ee16db8f4095c0d8d525f2367663f22a46b48d072c816e7fe19959') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

php composer.phar create-project --stability="stable" zendframework/skeleton-application $code_folder_name

docker build -t zonkone/zend-container:1.0.0 .

docker run -p 80:80 --name $1 -v $workdir/zend/:/var/www/html/ -d zonkone/zend-container:1.0.0
